"""add shipments

Revision ID: cc0dbee4e579
Revises: 48011be3052a
Create Date: 2026-02-18 20:29:24.810971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0dbee4e579'
down_revision: Union[str, Sequence[str], None] = '48011be3052a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_created_at'), 'shipments', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_user_id'), 'shipments', ['user_id'], unique=False)
    op.add_column('stock_moves', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_moves_shipment_id'), 'stock_moves', ['shipment_id'], unique=False)
    #op.create_foreign_key(None, 'stock_moves', 'shipments', ['shipment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'stock_moves', type_='foreignkey')
    op.drop_index(op.f('ix_stock_moves_shipment_id'), table_name='stock_moves')
    op.drop_column('stock_moves', 'shipment_id')
    op.drop_index(op.f('ix_shipments_user_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_created_at'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
